version: "3"
services:
  booking-db:
    container_name: booking-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${BOOKING_DBNAME}
      - MYSQL_TCP_PORT=4203
    ports:
      - "4203:4203"
    networks:
      - host

  bikenest-db:
    container_name: bikenest-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${BIKENEST_DBNAME}
      - MYSQL_TCP_PORT=4204
    ports:
      - "4204:4204"
    networks:
      - host

  user-db:
    container_name: user-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${USER_DBNAME}
      - MYSQL_TCP_PORT=4202
    ports:
      - "4202:4202"
    networks:
      - host

  payment-db:
    container_name: payment-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${PAYMENT_DBNAME}
      - MYSQL_TCP_PORT=4201
    ports:
      - "4201:4201"
    networks:
      - host

  raspi:
    container_name: raspi
    build:
      context: ../raspi-server
    restart: always
    networks:
      - host

  bikenest:
    container_name: bikenest
    build:
      context: service-bikenest
      dockerfile: Dockerfile_debug
    restart: always
    ports:
      - "5005:5005"
      - "9001:9001"
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - BIKENEST_DB_SERVICE_HOST=bikenest-db
      - RASPI_SERVICE_HOST=${RASPI_HOST}
      - RASPI_PORT=${RASPI_PORT}
      - MYSQL_PORT=4204
      - MYSQL_DBNAME=${BIKENEST_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - host

  booking:
    container_name: booking
    build:
      context: service-booking
      dockerfile: Dockerfile_debug
    restart: always
    ports:
      - "5006:5006"
      - "9002:9002"
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - BOOKING_DB_SERVICE_HOST=booking-db
      - RASPI_SERVICE_HOST=${RASPI_HOST}
      - RASPI_PORT=${RASPI_PORT}
      - MYSQL_PORT=4203
      - MYSQL_DBNAME=${BOOKING_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - host

  gateway:
    container_name: gateway
    build:
      context: apigateway
      dockerfile: Dockerfile_debug
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - RASPI_SERVICE_HOST=${RASPI_HOST}
      - RASPI_PORT=${RASPI_PORT}
    ports:
      - "9000:9000"
      - "5007:5007"
    networks:
      - host

  usermgmt:
    container_name: usermgmt
    build:
      context: service-usermgmt
      dockerfile: Dockerfile_debug
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - USERMGMT_DB_SERVICE_HOST=user-db
      - RASPI_SERVICE_HOST=${RASPI_HOST}
      - RASPI_PORT=${RASPI_PORT}
      - MYSQL_PORT=4202
      - MYSQL_DBNAME=${USER_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "5008:5008"
      - "9003:9003"
    networks:
      - host

  payment:
    container_name: payment
    build:
      context: service-payment
      dockerfile: Dockerfile_debug
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - PAYMENT_DB_SERVICE_HOST=payment-db
      - RASPI_SERVICE_HOST=${RASPI_HOST}
      - RASPI_PORT=${RASPI_PORT}
      - MYSQL_PORT=4201
      - MYSQL_DBNAME=${PAYMENT_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "5009:5009"
      - "9004:9004"
    networks:
      - host
networks:
  host:
