version: "3.8"
services:
  booking-db:
    container_name: booking-db
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${BOOKING_DB_ROOTPW}
     - MYSQL_USER=${BOOKING_DB_USER}
     - MYSQL_PASSWORD=${BOOKING_DB_PASSWORD}
     - MYSQL_DATABASE=${BOOKING_DB_DATABASE}
    networks:
     - booking-db

  bikenest-db:
    container_name: bikenest-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${BIKENEST_DB_ROOTPW}
      - MYSQL_USER=${BIKENEST_DB_USER}
      - MYSQL_PASSWORD=${BIKENEST_DB_PASSWORD}
      - MYSQL_DATABASE=${BIKENEST_DB_DATABASE}
    networks:
     - bikenest-db

  user-db:
    container_name: user-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_ROOTPW}
      - MYSQL_USER=${USER_DB_USER}
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}
      - MYSQL_DATABASE=${USER_DB_DATABASE}
    networks:
      - user-db

  payment-db:
    container_name: payment-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PAYMENT_DB_ROOTPW}
      - MYSQL_USER=${PAYMENT_DB_USER}
      - MYSQL_PASSWORD=${PAYMENT_DB_PASSWORD}
      - MYSQL_DATABASE=${PAYMENT_DB_DATABASE}
    networks:
      - payment-db
  #php:
  #  container_name: phpadmin
  #  image: phpmyadmin/phpmyadmin
  #  ports:
  #   - "8080:80"
  #  environment:
  #   - PMA_HOST=booking-db
  #  networks:
  #   - booking-db

  bikenest:
    container_name: bikenest
    build: 
      context: service-bikenest
      dockerfile: Dockerfile_debug
    restart: always
    ports:
     - "5005:5005"
     - "9001:9001"
    environment:
     - MYSQL_HOST=bikenest-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=${BIKENEST_DB_DATABASE}
     - MYSQL_USER=${BIKENEST_DB_USER}
     - MYSQL_PASSWORD=${BIKENEST_DB_PASSWORD}
    networks:
     - services
     - bikenest-db
     
  booking:
    container_name: booking
    build: 
      context: service-booking
      dockerfile: Dockerfile_debug
    restart: always
    ports:
     - "5006:5006"
     - "9002:9002"
    environment:
     - MYSQL_HOST=booking-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=${BOOKING_DB_DATABASE}
     - MYSQL_USER=${BOOKING_DB_USER}
     - MYSQL_PASSWORD=${BOOKING_DB_PASSWORD}
    networks:
     - services
     - booking-db

  gateway:
    container_name: gateway
    build: 
      context: apigateway
      dockerfile: Dockerfile_debug
    restart: always
    ports:
     - "9000:9000"
     - "5007:5007"
    networks:
     - services
     
  usermgmt:
    container_name: usermgmt
    build: 
      context: service-usermgmt
      dockerfile: Dockerfile_debug
    restart: always
    environment:
      - MYSQL_HOST=user-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${USER_DB_DATABASE}
      - MYSQL_USER=${USER_DB_USER}
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}
    ports:
     - "5008:5008"
     - "9003:9003"
    networks:
     - services
     - user-db

  payment:
    container_name: payment
    build:
      context: service-payment
      dockerfile: Dockerfile_debug
    restart: always
    environment:
      - MYSQL_HOST=payment-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${PAYMENT_DB_DATABASE}
      - MYSQL_USER=${PAYMENT_DB_USER}
      - MYSQL_PASSWORD=${PAYMENT_DB_PASSWORD}
    ports:
      - "5009:5009"
      - "9004:9004"
    networks:
      - services
      - payment-db
networks:
  payment-db:
  user-db:
  booking-db:
  bikenest-db:
  services:
