version: "3.8"
services:
  booking-db:
    container_name: booking-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKING_DB_ROOTPW}
      - MYSQL_USER=${BOOKING_DB_USER}
      - MYSQL_PASSWORD=${BOOKING_DB_PASSWORD}
      - MYSQL_DATABASE=${BOOKING_DB_DATABASE}
    networks:
     - booking-db

  bikenest-db:
    container_name: bikenest-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${BIKENEST_DB_ROOTPW}
      - MYSQL_USER=${BIKENEST_DB_USER}
      - MYSQL_PASSWORD=${BIKENEST_DB_PASSWORD}
      - MYSQL_DATABASE=${BIKENEST_DB_DATABASE}
    networks:
     - bikenest-db

  user-db:
    container_name: user-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${USER_DB_ROOTPW}
      - MYSQL_USER=${USER_DB_USER}
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}
      - MYSQL_DATABASE=${USER_DB_DATABASE}
    networks:
      - user-db

  payment-db:
    container_name: payment-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PAYMENT_DB_ROOTPW}
      - MYSQL_USER=${PAYMENT_DB_USER}
      - MYSQL_PASSWORD=${PAYMENT_DB_PASSWORD}
      - MYSQL_DATABASE=${PAYMENT_DB_DATABASE}
    networks:
      - payment-db


  bikenest:
    container_name: bikenest
    build: service-bikenest
    restart: always
    environment:
     - MYSQL_HOST=bikenest-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=${BIKENEST_DB_DATABASE}
     - MYSQL_USER=${BIKENEST_DB_USER}
     - MYSQL_PASSWORD=${BIKENEST_DB_PASSWORD}
    networks:
     - bikenest-db
     - services
     
  booking:
    container_name: booking
    build: service-booking
    restart: always
    environment:
     - MYSQL_HOST=booking-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=${BOOKING_DB_DATABASE}
     - MYSQL_USER=${BOOKING_DB_USER}
     - MYSQL_PASSWORD=${BOOKING_DB_PASSWORD}
    networks:
     - booking-db
     - services
   
  gateway:
    container_name: gateway
    build: apigateway
    restart: always
    ports:
     - "9000:9000"
    networks:
     - services
     
  usermgmt:
    container_name: usermgmt
    build: service-usermgmt
    restart: always
    environment:
      - MYSQL_HOST=user-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${USER_DB_DATABASE}
      - MYSQL_USER=${USER_DB_USER}
      - MYSQL_PASSWORD=${USER_DB_PASSWORD}
    networks:
      - user-db
      - services

  payment:
    container_name: payment
    build: service-payment
    restart: always
    environment:
      - MYSQL_HOST=payment-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${PAYMENT_DB_DATABASE}
      - MYSQL_USER=${PAYMENT_DB_USER}
      - MYSQL_PASSWORD=${PAYMENT_DB_PASSWORD}
      - BT_MERCHANT_ID=${BT_MERCHANT_ID}
      - BT_PUBLIC_KEY=${BT_PUBLIC_KEY}
      - BT_PRIVATE_KEY=${BT_PRIVATE_KEY}
    networks:
      - services
      - payment-db

networks:
  payment-db:
  booking-db:
  bikenest-db:
  user-db:
  services:
