version: "3.8"
services:
  booking-db:
    container_name: booking-db
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_USER=bookingservice
     - MYSQL_PASSWORD=test
     - MYSQL_DATABASE=booking
    networks:
     - booking-db

  bikenest-db:
    container_name: bikenest-db
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_USER=bikenestservice
     - MYSQL_PASSWORD=test
     - MYSQL_DATABASE=bikenest
    networks:
     - bikenest-db
    
  #php:
  #  container_name: phpadmin
  #  image: phpmyadmin/phpmyadmin
  #  ports:
  #   - "8080:80"
  #  environment:
  #   - PMA_HOST=booking-db
  #  networks:
  #   - booking-db

  bikenest:
    container_name: bikenest
    build: 
      context: service-bikenest
      dockerfile: Dockerfile_debug
    restart: always
    ports:
     - "9001:9001"
     - "5005:5005"
    environment:
     - MYSQL_HOST=bikenest-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=bikenest
     - MYSQL_USER=bikenestservice
     - MYSQL_PASSWORD=test
     - _JAVA_OPTIONS=-Xms256m -Xmx384m -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
     - bikenest-db
     
  booking:
    container_name: booking
    build: 
      context: service-booking
      dockerfile: Dockerfile_debug
    restart: always
    ports:
     - "9002:9002"
     - "5006:5006"
    environment:
     - MYSQL_HOST=booking-db
     - MYSQL_PORT=3306
     - MYSQL_DBNAME=booking
     - MYSQL_USER=bookingservice
     - MYSQL_PASSWORD=test
     - _JAVA_OPTIONS=-Xms256m -Xmx384m -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
    networks:
     - booking-db

networks:
  booking-db:
  bikenest-db: