version: "3"
services:
  booking-db:
    container_name: booking-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${BOOKING_DBNAME}
    networks:
     - booking-db

  bikenest-db:
    container_name: bikenest-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${BIKENEST_DBNAME}
    networks:
     - bikenest-db

  user-db:
    container_name: user-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${USER_DBNAME}
    networks:
      - user-db

  payment-db:
    container_name: payment-db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${PAYMENT_DBNAME}
    networks:
      - payment-db


  bikenest:
    container_name: bikenest
    build: service-bikenest
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - BIKENEST_DB_SERVICE_HOST=bikenest-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${BIKENEST_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
     - bikenest-db
     - services
     
  booking:
    container_name: booking
    build: service-booking
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - BOOKING_DB_SERVICE_HOST=booking-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${BOOKING_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
     - booking-db
     - services
   
  gateway:
    container_name: gateway
    build: apigateway
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
    ports:
     - "9000:9000"
    networks:
     - services
     
  usermgmt:
    container_name: usermgmt
    build: service-usermgmt
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - USERMGMT_DB_SERVICE_HOST=user-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${USER_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - user-db
      - services

  payment:
    container_name: payment
    build: service-payment
    restart: always
    environment:
      - BOOKING_SERVICE_HOST=booking
      - PAYMENT_SERVICE_HOST=payment
      - USERMGMT_SERVICE_HOST=usermgmt
      - BIKENEST_SERVICE_HOST=bikenest
      - PAYMENT_DB_SERVICE_HOST=payment-db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=${PAYMENT_DBNAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - BT_MERCHANT_ID=${BT_MERCHANT_ID}
      - BT_PUBLIC_KEY=${BT_PUBLIC_KEY}
      - BT_PRIVATE_KEY=${BT_PRIVATE_KEY}
    networks:
      - services
      - payment-db

networks:
  payment-db:
  booking-db:
  bikenest-db:
  user-db:
  services:
