apiVersion: v1
items:

### Services for Conncetions
- apiVersion: v1
  kind: Service
  metadata:
    name: gateway
  spec:
    selector:
      service: gateway
    ports:
      - name: "9000"
        port: 9000
        targetPort: 9000
    type: LoadBalancer

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: gateway
    name: gateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: gateway
    strategy: {}
    template:
      metadata:
        labels:
          service: gateway
      spec:
        containers:
        - image: bikenest/backend:gateway
          imagePullPolicy: IfNotPresent
          name: gateway
          ports:
          - containerPort: 9000
          resources: {}
        imagePullSecrets:
          - name: dockerhub-credential
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}
