apiVersion: v1
items:

### Services for Conncetions
- apiVersion: v1
  kind: Service
  metadata:
    name: gateway
  spec:
    selector:
      service: gateway
    ports:
      - name: "9000"
        port: 9000
        targetPort: 9000
    type: LoadBalancer


- apiVersion: v1
  kind: Service
  metadata:
    name: bikenest-db
  spec:
    selector:
      service: bikenest-db
    ports:
      - name: "3306"
        port: 3306
        targetPort: 3306

- apiVersion: v1
  kind: Service
  metadata:
    name: bikenest
  spec:
    selector:
      service: bikenest
    ports:
      - name: "9001"
        port: 9001
        targetPort: 9001

### Deployments

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: gateway
    name: gateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: gateway
    strategy: {}
    template:
      metadata:
        labels:
          service: gateway
      spec:
        containers:
        - image: backend_gateway
          imagePullPolicy: IfNotPresent
          name: gateway
          ports:
          - containerPort: 9000
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
  
  
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: bikenest-db
    name: bikenest-db
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: bikenest-db
    strategy: {}
    template:
      metadata:
        labels:
          service: bikenest-db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: bikenest
          - name: MYSQL_PASSWORD
            value: test
          - name: MYSQL_ROOT_PASSWORD
            value: test
          - name: MYSQL_USER
            value: bikenestservice
          image: mysql
          imagePullPolicy: ""
          name: bikenest-db
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      service: bikenest
    name: bikenest
  spec:
    replicas: 1
    selector:
      matchLabels:
        service: bikenest
    strategy: {}
    template:
      metadata:
        labels:
          service: bikenest
      spec:
        containers:
        - env:
          - name: MYSQL_DBNAME
            value: bikenest
          - name: MYSQL_PASSWORD
            value: test
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            value: root
          image: backend_bikenest
          imagePullPolicy: IfNotPresent
          name: bikenest
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}

kind: List
metadata: {}