name: Backend Integration Tests (Gradle)

on: [push]

jobs:
  Backend-Integration-Tests:

    runs-on: ubuntu-latest
    env:
      backend: ./Backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    # For now use the node js script to wait on the docker containers
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    # Install the wait-on script, that can be used to wait until the docker containers are running.
    - name: Install wait-on script
      run: npm install -g wait-on
      
    # Build all projects
    - name: Build Services
      working-directory: ${{env.backend}}
      run: ./gradlew assemble

    # Start up all Database Docker Containers.
    - name: Start all Containers
      working-directory: ${{env.backend}}
      run: docker-compose -f docker-compose-testcontainers.yml --build up
            
    # Wait for all services to be up
    - run: wait-on http://localhost:9000
    - run: wait-on http://localhost:9001
    - run: wait-on http://localhost:9002
    - run: wait-on http://localhost:9003
    - run: wait-on http://localhost:9004
        
    # Execute all Integration tests
    - name: API Gateway Integration Tests
      working-directory: ${{env.backend}}
      run: ./gradlew :apigateway:test --tests com.bikenest.apigateway.integration.*

    - name: UserMGMT Service Integration Tests
      run: ./gradlew :service-usermgmt:test --tests com.bikenest.serviceusermgmt.integration.*

    - name: Bikenest Service Integration Tests
      working-directory: ${{env.backend}}
      run: ./gradlew :service-bikenest:test --tests com.bikenest.servicebikenest.integration.*

    - name: Booking Service Integration Tests
      working-directory: ${{env.backend}}
      run: ./gradlew :service-booking:test --tests com.bikenest.servicebooking.integration.*

    - name: Payment Service Integration Tests
      working-directory: ${{env.backend}}
      run: ./gradlew :service-payment:test --tests com.bikenest.servicepayment.integration.*
