# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Bikenest-Service CI Gradlew

on: [push]

jobs:
  unittest:

    runs-on: ubuntu-latest
    env:
      bikenest-service: ./Backend/service-bikenest
      booking-service: ./Backend/service-booking
      usermanagement-service: ./Backend/service-usermgmt
      apigateway: ./Backend/apigateway

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Execute rights for gradlew in Bikenest Service.
      working-directory: ${{env.bikenest-service}}
      run: chmod +x gradlew
    - name: Execute rights for gradlew in in Booking Service
      working-directory: ${{env.booking-service}}
      run: chmod +x gradlew
    - name: Execute rights for gradlew in in UserMGMT Service
      working-directory: ${{env.usermanagement-service}}
      run: chmod +x gradlew
    - name: Execute rights for gradlew in in API Gateway
      working-directory: ${{env.apigateway}}
      run: chmod +x gradlew
    - name: Bikenest Service Unit Tests
      working-directory: ${{env.bikenest-service}}
      run: ./gradlew test --tests com.bikenest.servicebikenest.unit.*
    - name: Booking Service Unit Tests
      working-directory: ${{env.booking-service}}
      run: ./gradlew test --tests com.bikenest.servicebooking.unit.*
    - name: UserMGMT Service Unit Tests
      working-directory: ${{env.usermanagement-service}}
      run: ./gradlew test --tests com.bikenest.serviceusermgmt.unit.*
    - name: API Gateway Unit Tests
      working-directory: ${{env.apigateway}}
      run: ./gradlew test --tests com.bikenest.apigateway.unit.*
