# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Bikenest-Service CI Gradlew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Bikenest Service Unit Tests
      run: ./Backend/service-bikenest/gradlew test --tests com.bikenest.servicebikenest.unit.*
    - name: Booking Service Unit Tests
      run: ./Backend/service-booking/gradlew test --tests com.bikenest.servicebooking.unit.*
